### PR TITLE
Multi file sign

### PR DESCRIPTION
**Pull request by eb-oss**

### CODE REVIEW

**Review by tykeal — COMMENTED** [review]
Please squash these two changes into this one:

def04d2 and e0584dd

And rebase the whole series so that eddf2f2 can be completely dropped. Each commit should be passing all CI, not putting in fix commits that paper over previous issues.

**Review by tykeal — CHANGES_REQUESTED** [review]
Please squash these two changes into this one:

def04d2 and e0584dd

And rebase the whole series so that eddf2f2 can be completely dropped. Each commit should be passing all CI, not putting in fix commits that paper over previous issues.

**Comment by eb-oss** [comment]
> Please squash these two changes into this one:
> 
> [def04d2](https://github.com/lfit/sigul-sign-action/commit/def04d21fc801412f94db3bb3a204f815c1bbad9) and [e0584dd](https://github.com/lfit/sigul-sign-action/commit/e0584dd5a608f3f7cc9ae24af9bb7d34f1b99ae7)
> 
> And rebase the whole series so that [eddf2f2](https://github.com/lfit/sigul-sign-action/commit/eddf2f2bf525bb2b0a9a4d4e79e7fb30b1848a44) can be completely dropped. Each commit should be passing all CI, not putting in fix commits that paper over previous issues.

Done.

**Review by tykeal — APPROVED** [review]

**Review by tykeal — CHANGES_REQUESTED** [review]
This all looks good. I initially approved it, but we've got the following feature turned on:

Require signed commits.

This means that _all_ of the commits need to be GPG signed _and_ that you have uploaded your public key to your GitHub profile.

Get that done and we should be good to go!

**Review by tykeal — APPROVED** [review]

**Pull request merged**
